language: php

env:
  - DB=mysql

branches:
  only:
    - master
    - development

services:
  - mysql

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.1
  - nightly
  - hhvm

matrix:
  fast_finish: true
  allow_failures:
    - php: 5.3
    - php: 5.4
    - php: 5.5
    - php: nightly
    - php: hhvm

install:
    - composer self-update
    - composer install

before_script:
  - if [[ "$DB" == "mysql" ]]; then mysql -e "CREATE DATABASE IF NOT EXISTS testdb;" -uroot; fi

script: php vendor/bin/codecept run --debug

cache:
  directories:
    - $HOME/.composer/cache
